name: freeform
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4
  - pandas=1.5.3
  - tqdm=4.66.4
  - matplotlib=3.8.0
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - tabulate=0.9.0
  - tabpfn=0.1.10
  - xgboost=2.1.1
  - graphviz=0.20.3
  - openai=1.40.8
  - together=1.2.3
  - pickle
  - python=3.9.16